# Concatenate src/*.js (shared first) into the shippable bundle prism.js.
$ErrorActionPreference = 'Stop'
Set-Location $PSScriptRoot

$out = 'prism.js'
$files = @(
  'src/prism-shared.js',
  'src/prism-stat-card.js',
  'src/prism-gauge-card.js',
  'src/prism-sparkline-card.js',
  'src/prism-power-card.js',
  'src/prism-bar-card.js',
  'src/prism-linear-gauge-card.js',
  'src/prism-entities-card.js',
  'src/prism-filter-card.js',
  'src/prism-switch-card.js',
  'src/prism-light-card.js',
  'src/prism-climate-card.js',
  'src/prism-cover-card.js',
  'src/prism-media-card.js',
  'src/prism-wind-card.js',
  'src/prism-weather-card.js',
  'src/prism-forecast-card.js'
)

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('/* Prism — bundled cards. Generated by build.ps1; do not edit directly. */')
[void]$sb.AppendLine('/* Edit files in src/ and re-run build.ps1 */')
foreach ($f in $files) {
  [void]$sb.AppendLine('')
  [void]$sb.AppendLine("/* ===== $f ===== */")
  [void]$sb.AppendLine((Get-Content $f -Raw))
}
Set-Content -Path $out -Value $sb.ToString() -Encoding utf8 -NoNewline
Write-Output "Built $out from $($files.Count) sources ($((Get-Item $out).Length) bytes)."
