#!/usr/bin/env bash
# Concatenate src/*.js (shared first) into the shippable bundle prism.js.
set -euo pipefail
cd "$(dirname "$0")"

OUT="prism.js"
FILES=(
  "src/prism-shared.js"
  "src/prism-stat-card.js"
  "src/prism-gauge-card.js"
  "src/prism-sparkline-card.js"
  "src/prism-power-card.js"
  "src/prism-bar-card.js"
  "src/prism-linear-gauge-card.js"
)

{
  echo "/* Prism — bundled cards. Generated by build.sh; do not edit directly. */"
  echo "/* Edit files in src/ and re-run ./build.sh */"
  for f in "${FILES[@]}"; do
    echo ""
    echo "/* ===== $f ===== */"
    cat "$f"
  done
} > "$OUT"

echo "Built $OUT from ${#FILES[@]} sources ($(wc -c < "$OUT") bytes)."
