/* Prism — bundled cards. Generated by build.sh; do not edit directly. */
/* Edit files in src/ and re-run ./build.sh */

/* ===== src/prism-shared.js ===== */
/**
 * Prism — shared runtime for all Prism cards.
 *
 * Exposes a single global namespace, `window.PrismUI`, holding the design
 * tokens, formatting helpers, and a reusable config-editor base class that
 * every Prism card builds on. Load this before any individual card file
 * (the bundled `prism.js` already concatenates them in the right order).
 *
 * Design language: flat, minimal, data-first. No 3D, no heavy shadows.
 * All surfaces/colours resolve from CSS custom properties so a Prism card
 * automatically follows the active Home Assistant theme — and picks up the
 * richer flat look when the `Prism` theme (themes/prism.yaml) is active.
 */
(function () {
  'use strict';

  if (window.PrismUI && window.PrismUI.version) return; // already loaded

  const VERSION = '0.1.0';

  // ── Named accent presets ──────────────────────────────────────────
  // Selectable in every card editor; a card may also use a raw hex value.
  const ACCENTS = {
    blue:   '#3aa0e8',
    teal:   '#28b5a6',
    green:  '#3aa76d',
    amber:  '#e0922e',
    orange: '#e8703a',
    red:    '#c64b4b',
    pink:   '#d1568f',
    purple: '#8a6fd6',
    slate:  '#5b6b78',
  };

  // ── Formatting / value helpers ────────────────────────────────────
  function esc(s) {
    return String(s ?? '')
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }

  // Numeric state of an entity, or NaN.
  function num(hass, entityId) {
    if (!entityId || !hass) return NaN;
    const s = hass.states[entityId];
    if (!s) return NaN;
    return parseFloat(s.state);
  }

  function clamp(v, lo, hi) {
    return Math.min(hi, Math.max(lo, v));
  }

  // Format a number with a fixed decimal count and thousands separators.
  function fmtNumber(value, decimals) {
    if (value == null || isNaN(value)) return '—';
    const d = decimals == null ? 0 : decimals;
    return Number(value).toLocaleString(undefined, {
      minimumFractionDigits: d,
      maximumFractionDigits: d,
    });
  }

  // Resolve a card's accent config into a usable CSS colour.
  // Accepts a preset name ("blue"), a raw hex ("#ff8800"), any CSS colour,
  // or "theme" / undefined to defer to the --prism-accent theme token.
  function resolveAccent(accent) {
    if (!accent || accent === 'theme') return 'var(--prism-accent, #3aa0e8)';
    if (ACCENTS[accent]) return ACCENTS[accent];
    return accent; // raw hex / css colour
  }

  // Unit of an entity (config override wins).
  function unitOf(hass, entityId, override) {
    if (override != null && override !== '') return override;
    return hass?.states?.[entityId]?.attributes?.unit_of_measurement ?? '';
  }

  function friendlyName(hass, entityId) {
    return hass?.states?.[entityId]?.attributes?.friendly_name ?? entityId ?? '';
  }

  // ── Shared token stylesheet ───────────────────────────────────────
  // Injected into every card's shadow root. Each token falls back through
  // the Prism theme token → native HA token → hard default, so cards look
  // right with or without the Prism theme installed, in light and dark.
  const TOKEN_STYLE = `
    :host {
      --_accent: var(--prism-accent, var(--primary-color, #3aa0e8));
      --_surface: var(--prism-surface, var(--ha-card-background, var(--card-background-color, #fff)));
      --_surface-2: var(--prism-surface-2, color-mix(in srgb, var(--_surface) 94%, #808c96 6%));
      --_text: var(--prism-text-primary, var(--primary-text-color, #15181a));
      --_text-2: var(--prism-text-secondary, var(--secondary-text-color, #7c8084));
      --_border: var(--prism-border, var(--divider-color, rgba(120,130,140,.16)));
      --_radius: var(--prism-radius, var(--ha-card-border-radius, 18px));
      --_shadow: var(--prism-shadow, none);
      --_good: var(--prism-good, var(--success-color, #3aa76d));
      --_warn: var(--prism-warn, var(--warning-color, #e0922e));
      --_bad: var(--prism-bad, var(--error-color, #c64b4b));
      --_gap: var(--prism-gap, 16px);
      --_font: var(--prism-font, var(--paper-font-body1_-_font-family, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif));
      display: block;
    }
    .prism-card {
      box-sizing: border-box;
      width: 100%;
      height: 100%;
      background: var(--_surface);
      color: var(--_text);
      border: 1px solid var(--_border);
      border-radius: var(--_radius);
      box-shadow: var(--_shadow);
      padding: var(--_gap);
      font-family: var(--_font);
      -webkit-font-smoothing: antialiased;
    }
    .prism-head {
      display: flex; align-items: center; justify-content: space-between;
      gap: 8px; margin-bottom: 10px;
    }
    .prism-title {
      font-size: 13px; font-weight: 600; color: var(--_text-2);
      letter-spacing: .01em; white-space: nowrap; overflow: hidden;
      text-overflow: ellipsis;
    }
    @media (prefers-reduced-motion: reduce) {
      * { animation: none !important; transition: none !important; }
    }
  `;

  // ── History / geometry helpers (shared by stat + sparkline) ───────

  // Fetch numeric history for an entity over the last `hours`.
  // Returns [{ t: epoch_ms, v: number }] sorted ascending. Never throws.
  async function fetchHistory(hass, entityId, hours) {
    if (!hass || !entityId) return [];
    const end = new Date();
    const start = new Date(end.getTime() - hours * 3600 * 1000);
    try {
      const res = await hass.callWS({
        type: 'history/history_during_period',
        start_time: start.toISOString(),
        end_time: end.toISOString(),
        entity_ids: [entityId],
        minimal_response: true,
        no_attributes: true,
      });
      const arr = (res && res[entityId]) || [];
      const out = [];
      for (const p of arr) {
        const t = p.lu != null ? p.lu * 1000
          : p.last_updated ? Date.parse(p.last_updated)
          : p.last_changed ? Date.parse(p.last_changed) : NaN;
        const v = parseFloat(p.s ?? p.state);
        if (!isNaN(t) && !isNaN(v)) out.push({ t, v });
      }
      return out.sort((a, b) => a.t - b.t);
    } catch (e) {
      return [];
    }
  }

  // Largest-Triangle-Three-Buckets-ish downsample (cheap): even stride.
  function downsample(points, maxPoints) {
    if (points.length <= maxPoints) return points;
    const stride = points.length / maxPoints;
    const out = [];
    for (let i = 0; i < maxPoints; i++) out.push(points[Math.floor(i * stride)]);
    out.push(points[points.length - 1]);
    return out;
  }

  // Build SVG line + area paths for a series inside a w×h box (with padding).
  // Returns { line, area, min, max, first, last } — all coordinates in the box.
  function sparklinePath(points, w, h, pad = 2) {
    if (!points.length) return { line: '', area: '', min: NaN, max: NaN, first: NaN, last: NaN };
    let min = Infinity, max = -Infinity;
    for (const p of points) { if (p.v < min) min = p.v; if (p.v > max) max = p.v; }
    if (min === max) { min -= 1; max += 1; } // flat line → centre it
    const t0 = points[0].t, t1 = points[points.length - 1].t;
    const span = t1 - t0 || 1;
    const range = max - min || 1;
    const x = (t) => pad + ((t - t0) / span) * (w - pad * 2);
    const y = (v) => pad + (1 - (v - min) / range) * (h - pad * 2);
    let line = '';
    points.forEach((p, i) => {
      line += `${i ? 'L' : 'M'}${x(p.t).toFixed(1)} ${y(p.v).toFixed(1)}`;
    });
    const area = `${line}L${x(t1).toFixed(1)} ${(h - pad).toFixed(1)}L${x(t0).toFixed(1)} ${(h - pad).toFixed(1)}Z`;
    return { line, area, min, max, first: points[0].v, last: points[points.length - 1].v };
  }

  // ── Card registry helper ──────────────────────────────────────────
  function registerCard(entry) {
    window.customCards = window.customCards || [];
    if (!window.customCards.some((c) => c.type === entry.type)) {
      window.customCards.push(Object.assign({ preview: true }, entry));
    }
  }

  // ══════════════════════════════════════════════════════════════════
  //  Base config editor
  //  Provides the common plumbing + form controls every Prism editor
  //  needs: entity pickers, text/number fields, dropdowns, an accent
  //  picker (preset + custom hex), switches, and section headers.
  // ══════════════════════════════════════════════════════════════════
  class PrismEditor extends HTMLElement {
    constructor() {
      super();
      this.attachShadow({ mode: 'open' });
      this._config = null;
      this._hass = null;
      this._lastFired = null;
    }

    connectedCallback() {
      if (this._config) this._render();
    }

    set hass(hass) {
      this._hass = hass;
      this.shadowRoot.querySelectorAll('ha-entity-picker').forEach((p) => {
        p.hass = hass;
      });
    }

    setConfig(config) {
      const s = JSON.stringify(config);
      if (s === this._lastFired) return;
      this._config = JSON.parse(s);
      this._render();
    }

    _fire(config) {
      this._lastFired = JSON.stringify(config);
      this._config = config;
      this.dispatchEvent(
        new CustomEvent('config-changed', {
          detail: { config },
          bubbles: true,
          composed: true,
        })
      );
    }

    // Set/remove a single key and fire.
    _patch(key, value) {
      const cfg = { ...this._config };
      if (value === '' || value == null) delete cfg[key];
      else cfg[key] = value;
      this._fire(cfg);
    }

    // ── Controls ────────────────────────────────────────────────────
    _tf(label, value, onChange, opts = {}) {
      const el = document.createElement('ha-textfield');
      el.label = label;
      el.value = value ?? '';
      el.style.width = '100%';
      if (opts.type) el.type = opts.type;
      if (opts.suffix) el.suffix = opts.suffix;
      el.addEventListener('change', (e) => {
        const v = e.target.value;
        onChange(opts.type === 'number' ? (v === '' ? '' : Number(v)) : v.trim());
      });
      return el;
    }

    _picker(label, value, onChange, opts = {}) {
      const el = document.createElement('ha-entity-picker');
      if (this._hass) el.hass = this._hass;
      el.value = value ?? '';
      el.label = label;
      el.style.width = '100%';
      el.allowCustomEntity = true;
      if (opts.domains) el.includeDomains = opts.domains;
      el.addEventListener('value-changed', (e) => onChange(e.detail.value));
      return el;
    }

    _select(label, options, value, onChange) {
      const wrap = document.createElement('div');
      wrap.className = 'field';
      const lbl = document.createElement('label');
      lbl.className = 'lbl';
      lbl.textContent = label;
      const sel = document.createElement('select');
      sel.className = 'sel';
      options.forEach((opt) => {
        const o = document.createElement('option');
        const val = typeof opt === 'object' ? opt.value : opt;
        const txt = typeof opt === 'object' ? opt.label : opt;
        o.value = val;
        o.textContent = txt;
        if (val === value) o.selected = true;
        sel.appendChild(o);
      });
      sel.addEventListener('change', (e) => onChange(e.target.value));
      wrap.append(lbl, sel);
      return wrap;
    }

    _switch(label, value, onChange) {
      const wrap = document.createElement('div');
      wrap.className = 'field row';
      const lbl = document.createElement('label');
      lbl.className = 'lbl';
      lbl.textContent = label;
      const sw = document.createElement('ha-switch');
      sw.checked = !!value;
      sw.addEventListener('change', (e) => onChange(e.target.checked));
      wrap.append(lbl, sw);
      return wrap;
    }

    // Accent picker: preset dropdown + custom colour input that stay in sync.
    _accentField(value, onChange) {
      const wrap = document.createElement('div');
      wrap.className = 'field';
      const lbl = document.createElement('label');
      lbl.className = 'lbl';
      lbl.textContent = 'Accent colour';

      const row = document.createElement('div');
      row.className = 'accent-row';

      const sel = document.createElement('select');
      sel.className = 'sel';
      const opts = ['theme', ...Object.keys(ACCENTS), 'custom'];
      const isPreset = value == null || value === 'theme' || ACCENTS[value];
      opts.forEach((name) => {
        const o = document.createElement('option');
        o.value = name;
        o.textContent = name;
        if ((name === (value ?? 'theme')) || (name === 'custom' && !isPreset)) {
          o.selected = true;
        }
        sel.appendChild(o);
      });

      const color = document.createElement('input');
      color.type = 'color';
      color.className = 'color';
      color.value = ACCENTS[value] || (!isPreset ? value : '#3aa0e8');
      color.style.display = isPreset ? 'none' : 'inline-block';

      sel.addEventListener('change', (e) => {
        const v = e.target.value;
        if (v === 'custom') {
          color.style.display = 'inline-block';
          onChange(color.value);
        } else {
          color.style.display = 'none';
          onChange(v === 'theme' ? '' : v);
        }
      });
      color.addEventListener('input', (e) => onChange(e.target.value));

      row.append(sel, color);
      wrap.append(lbl, row);
      return wrap;
    }

    _section(text) {
      const h = document.createElement('div');
      h.className = 'section';
      h.textContent = text;
      return h;
    }

    _hint(text) {
      const h = document.createElement('div');
      h.className = 'hint';
      h.textContent = text;
      return h;
    }

    _baseStyle() {
      const style = document.createElement('style');
      style.textContent = `
        :host { display:block; padding:4px 0 12px; }
        .stack { display:flex; flex-direction:column; gap:12px; }
        .field { display:flex; flex-direction:column; gap:5px; }
        .field.row { flex-direction:row; align-items:center; justify-content:space-between; }
        .lbl { font:500 12px/1.2 var(--paper-font-body1_-_font-family, sans-serif); color:var(--secondary-text-color,#757575); }
        .sel {
          width:100%; box-sizing:border-box; padding:12px 10px; border-radius:6px;
          border:1px solid var(--divider-color,#ccc);
          background:var(--card-background-color,#fff); color:var(--primary-text-color,#212121);
          font:400 14px/1.2 inherit; cursor:pointer;
        }
        .accent-row { display:flex; gap:8px; align-items:center; }
        .accent-row .sel { flex:1; }
        .color { width:44px; height:44px; padding:0; border:1px solid var(--divider-color,#ccc); border-radius:6px; background:none; cursor:pointer; }
        .section { font:600 12px/1 var(--paper-font-body1_-_font-family, sans-serif); text-transform:uppercase; letter-spacing:.06em; color:var(--secondary-text-color,#757575); margin-top:8px; padding-top:12px; border-top:1px solid var(--divider-color,rgba(0,0,0,.08)); }
        .hint { font:400 11px/1.4 var(--paper-font-body1_-_font-family, sans-serif); color:var(--secondary-text-color,#757575); }
        ha-textfield, ha-entity-picker { width:100%; }
      `;
      return style;
    }

    // Subclasses implement _fields(stack) to append their controls.
    _render() {
      if (!this._config) return;
      this.shadowRoot.innerHTML = '';
      this.shadowRoot.appendChild(this._baseStyle());
      const stack = document.createElement('div');
      stack.className = 'stack';
      this._fields(stack);
      this.shadowRoot.appendChild(stack);
    }

    _fields() {
      /* implemented by subclass */
    }
  }

  // ── Export namespace ──────────────────────────────────────────────
  window.PrismUI = {
    version: VERSION,
    ACCENTS,
    TOKEN_STYLE,
    esc,
    num,
    clamp,
    fmtNumber,
    resolveAccent,
    unitOf,
    friendlyName,
    fetchHistory,
    downsample,
    sparklinePath,
    registerCard,
    PrismEditor,
  };

  // Friendly console banner (once).
  if (!window.__prismBanner) {
    window.__prismBanner = true;
    // eslint-disable-next-line no-console
    console.info(
      `%c PRISM %c ${VERSION} `,
      'background:#3aa0e8;color:#fff;font-weight:700;border-radius:4px 0 0 4px;padding:2px 6px;',
      'background:#15181a;color:#fff;border-radius:0 4px 4px 0;padding:2px 6px;'
    );
  }
})();

/* ===== src/prism-stat-card.js ===== */
/**
 * prism-stat-card
 * Flat KPI tile: one dominant value with a label, unit, optional icon,
 * a trend delta over a configurable window, and an optional inline
 * sparkline. Built for stats / energy dashboards — never a bare number.
 *
 * type: custom:prism-stat-card
 */
(function () {
  'use strict';
  const P = window.PrismUI;

  // ── Editor ────────────────────────────────────────────────────────
  class PrismStatCardEditor extends P.PrismEditor {
    _fields(stack) {
      const c = this._config;
      stack.append(
        this._picker('Entity (required)', c.entity, (v) => this._patch('entity', v)),
        this._tf('Name (optional)', c.name, (v) => this._patch('name', v)),
        this._tf('Icon (mdi:…)', c.icon, (v) => this._patch('icon', v)),
        this._tf('Unit override', c.unit, (v) => this._patch('unit', v)),
        this._tf('Decimals', c.decimals, (v) => this._patch('decimals', v), { type: 'number' }),
        this._accentField(c.accent, (v) => this._patch('accent', v)),
        this._section('Trend & graph'),
        this._switch('Show trend', c.trend !== false, (v) => this._patch('trend', v)),
        this._tf('Trend window (hours)', c.trend_hours, (v) => this._patch('trend_hours', v), { type: 'number' }),
        this._switch('Higher is worse (invert colour)', !!c.invert_trend, (v) => this._patch('invert_trend', v)),
        this._switch('Show sparkline', !!c.sparkline, (v) => this._patch('sparkline', v)),
        this._hint('Trend and sparkline read recorder history for the entity.')
      );
    }
  }
  customElements.define('prism-stat-card-editor', PrismStatCardEditor);

  // ── Card ──────────────────────────────────────────────────────────
  class PrismStatCard extends HTMLElement {
    constructor() {
      super();
      this.attachShadow({ mode: 'open' });
      this._config = null;
      this._hass = null;
      this._history = [];
      this._historyAt = 0;
    }

    setConfig(config) {
      if (!config.entity) throw new Error('prism-stat-card: `entity` is required.');
      this._config = { ...config };
      this._history = [];
      this._historyAt = 0;
      if (this._hass) this._render();
    }

    set hass(hass) {
      this._hass = hass;
      this._maybeFetchHistory();
      this._render();
    }

    getCardSize() { return this._config?.sparkline ? 3 : 2; }
    getGridOptions() {
      return this._config?.sparkline
        ? { rows: 3, columns: 6, min_rows: 2, min_columns: 3 }
        : { rows: 2, columns: 6, min_rows: 2, min_columns: 3 };
    }

    static getConfigElement() { return document.createElement('prism-stat-card-editor'); }
    static getStubConfig(hass) {
      const ent = hass ? Object.keys(hass.states).find((e) => e.startsWith('sensor.')) : 'sensor.example';
      return { entity: ent || 'sensor.example', trend: true, trend_hours: 24, sparkline: true, accent: 'blue' };
    }

    _needsHistory() {
      return this._config && (this._config.trend !== false || this._config.sparkline);
    }

    async _maybeFetchHistory() {
      if (!this._needsHistory() || !this._hass) return;
      const now = Date.now();
      if (now - this._historyAt < 5 * 60 * 1000 && this._history.length) return; // 5-min cache
      this._historyAt = now;
      const hours = Number(this._config.trend_hours) > 0 ? Number(this._config.trend_hours) : 24;
      const raw = await P.fetchHistory(this._hass, this._config.entity, hours);
      this._history = P.downsample(raw, 200);
      this._render();
    }

    _onTap() {
      this.dispatchEvent(new CustomEvent('hass-more-info', {
        detail: { entityId: this._config.entity }, bubbles: true, composed: true,
      }));
    }

    _render() {
      if (!this._config || !this._hass) return;
      const c = this._config;
      const hass = this._hass;
      const st = hass.states[c.entity];
      const accent = P.resolveAccent(c.accent);
      const name = c.name || (st ? st.attributes.friendly_name : c.entity);
      const raw = P.num(hass, c.entity);
      const isNumeric = !isNaN(raw);
      const unit = P.unitOf(hass, c.entity, c.unit);
      const value = !st ? '—'
        : isNumeric ? P.fmtNumber(raw, c.decimals != null ? Number(c.decimals) : inferDecimals(raw))
        : st.state;

      // Trend from history.
      let trendHtml = '';
      if (c.trend !== false && isNumeric && this._history.length > 1) {
        const first = this._history[0].v;
        const delta = raw - first;
        const pct = first !== 0 ? (delta / Math.abs(first)) * 100 : 0;
        const up = delta > 0;
        const flat = Math.abs(delta) < 1e-9;
        const worse = c.invert_trend ? up : !up;
        const col = flat ? 'var(--_text-2)' : worse ? 'var(--_bad)' : 'var(--_good)';
        const arrow = flat ? '→' : up ? '▲' : '▼';
        trendHtml = `<span class="trend" style="color:${col}">${arrow} ${P.esc(P.fmtNumber(Math.abs(pct), 1))}%</span>`;
      }

      // Sparkline.
      let sparkHtml = '';
      if (c.sparkline && this._history.length > 1) {
        const w = 240, h = 40;
        const sp = P.sparklinePath(this._history, w, h, 3);
        sparkHtml = `
          <svg class="spark" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" aria-hidden="true">
            <path d="${sp.area}" fill="${accent}" opacity="0.10"/>
            <path d="${sp.line}" fill="none" stroke="${accent}" stroke-width="2"
                  stroke-linecap="round" stroke-linejoin="round"/>
          </svg>`;
      }

      const iconHtml = c.icon
        ? `<div class="icon" style="color:${accent}"><ha-icon icon="${P.esc(c.icon)}"></ha-icon></div>`
        : '';

      this.shadowRoot.innerHTML = `
        <style>
          ${P.TOKEN_STYLE}
          .prism-card { display:flex; flex-direction:column; cursor:pointer; }
          .top { display:flex; align-items:center; gap:10px; margin-bottom:6px; }
          .icon { --mdc-icon-size:20px; width:34px; height:34px; border-radius:10px;
                  display:flex; align-items:center; justify-content:center;
                  background:color-mix(in srgb, ${accent} 14%, transparent); flex:none; }
          .label { font-size:13px; font-weight:600; color:var(--_text-2);
                   white-space:nowrap; overflow:hidden; text-overflow:ellipsis; }
          .valrow { display:flex; align-items:baseline; gap:8px; flex-wrap:wrap; }
          .value { font-size:34px; font-weight:750; line-height:1.05; letter-spacing:-.02em; color:var(--_text); }
          .unit { font-size:14px; font-weight:500; color:var(--_text-2); }
          .trend { font-size:13px; font-weight:600; margin-left:auto; }
          .spark { width:100%; height:40px; margin-top:auto; padding-top:10px; display:block; }
        </style>
        <div class="prism-card" role="button" tabindex="0" aria-label="${P.esc(name)}">
          <div class="top">
            ${iconHtml}
            <div class="label">${P.esc(name)}</div>
          </div>
          <div class="valrow">
            <span class="value">${P.esc(value)}</span>
            ${unit && isNumeric ? `<span class="unit">${P.esc(unit)}</span>` : ''}
            ${trendHtml}
          </div>
          ${sparkHtml}
        </div>`;

      const card = this.shadowRoot.querySelector('.prism-card');
      card.addEventListener('click', () => this._onTap());
      card.addEventListener('keydown', (e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); this._onTap(); } });
    }
  }

  // Sensible default decimals based on magnitude.
  function inferDecimals(v) {
    const a = Math.abs(v);
    if (a >= 100) return 0;
    if (a >= 10) return 1;
    return 2;
  }

  customElements.define('prism-stat-card', PrismStatCard);
  P.registerCard({
    type: 'prism-stat-card',
    name: 'Prism Stat Card',
    description: 'Flat KPI tile with trend delta and optional sparkline.',
  });
})();

/* ===== src/prism-gauge-card.js ===== */
/**
 * prism-gauge-card
 * Flat 270° radial gauge with configurable severity bands. Two looks:
 *   • fill  (default) — thin track + progress arc coloured by active band
 *   • bands           — full band arc + minimal needle
 * Big centred value, unit, and label underneath.
 *
 * type: custom:prism-gauge-card
 */
(function () {
  'use strict';
  const P = window.PrismUI;

  const START = 225; // math degrees (0 = east, CCW+); arc opens at the bottom
  const SWEEP = 270; // total degrees
  const END = START - SWEEP; // -45

  function pt(cx, cy, r, deg) {
    const rad = (deg * Math.PI) / 180;
    return [cx + r * Math.cos(rad), cy - r * Math.sin(rad)];
  }
  // Clockwise arc from a0 down to a1 (a0 > a1).
  function arc(cx, cy, r, a0, a1) {
    const [x0, y0] = pt(cx, cy, r, a0);
    const [x1, y1] = pt(cx, cy, r, a1);
    const large = Math.abs(a0 - a1) > 180 ? 1 : 0;
    return `M${x0.toFixed(2)} ${y0.toFixed(2)} A${r} ${r} 0 ${large} 1 ${x1.toFixed(2)} ${y1.toFixed(2)}`;
  }
  const degAt = (f) => START - P.clamp(f, 0, 1) * SWEEP;

  // ── Editor ────────────────────────────────────────────────────────
  class PrismGaugeCardEditor extends P.PrismEditor {
    _fields(stack) {
      const c = this._config;
      stack.append(
        this._picker('Entity (required)', c.entity, (v) => this._patch('entity', v)),
        this._tf('Name (optional)', c.name, (v) => this._patch('name', v)),
        this._tf('Unit override', c.unit, (v) => this._patch('unit', v)),
        this._tf('Minimum', c.min, (v) => this._patch('min', v), { type: 'number' }),
        this._tf('Maximum', c.max, (v) => this._patch('max', v), { type: 'number' }),
        this._tf('Decimals', c.decimals, (v) => this._patch('decimals', v), { type: 'number' }),
        this._select('Style', ['fill', 'bands'], c.style || 'fill', (v) => this._patch('style', v)),
        this._accentField(c.accent, (v) => this._patch('accent', v)),
        this._section('Severity bands'),
        this._hint('JSON array, e.g. [{"from":0,"color":"green"},{"from":60,"color":"amber"},{"from":85,"color":"red"}]. Colours accept preset names or hex.'),
        this._segmentsField(c.segments)
      );
    }

    _segmentsField(value) {
      const wrap = document.createElement('div');
      wrap.className = 'field';
      const ta = document.createElement('textarea');
      ta.rows = 5;
      ta.className = 'sel';
      ta.style.fontFamily = 'monospace';
      ta.value = JSON.stringify(value ?? [], null, 2);
      ta.addEventListener('change', (e) => {
        try { this._patch('segments', JSON.parse(e.target.value)); } catch (_) { /* wait for valid JSON */ }
      });
      wrap.appendChild(ta);
      return wrap;
    }
  }
  customElements.define('prism-gauge-card-editor', PrismGaugeCardEditor);

  // ── Card ──────────────────────────────────────────────────────────
  class PrismGaugeCard extends HTMLElement {
    constructor() {
      super();
      this.attachShadow({ mode: 'open' });
      this._config = null;
      this._hass = null;
    }

    setConfig(config) {
      if (!config.entity) throw new Error('prism-gauge-card: `entity` is required.');
      this._config = { min: 0, max: 100, style: 'fill', ...config };
      if (this._hass) this._render();
    }

    set hass(hass) { this._hass = hass; this._render(); }

    getCardSize() { return 4; }
    getGridOptions() { return { rows: 4, columns: 6, min_rows: 3, min_columns: 3 }; }

    static getConfigElement() { return document.createElement('prism-gauge-card-editor'); }
    static getStubConfig(hass) {
      const ent = hass ? Object.keys(hass.states).find((e) => e.startsWith('sensor.')) : 'sensor.example';
      return {
        entity: ent || 'sensor.example', min: 0, max: 100, style: 'fill',
        segments: [{ from: 0, color: 'green' }, { from: 60, color: 'amber' }, { from: 85, color: 'red' }],
      };
    }

    _segColor(value) {
      const segs = Array.isArray(this._config.segments) ? this._config.segments : [];
      if (!segs.length) return P.resolveAccent(this._config.accent);
      const sorted = [...segs].sort((a, b) => a.from - b.from);
      let col = P.resolveAccent(sorted[0].color);
      for (const s of sorted) if (value >= s.from) col = P.resolveAccent(s.color);
      return col;
    }

    _render() {
      if (!this._config || !this._hass) return;
      const c = this._config;
      const hass = this._hass;
      const st = hass.states[c.entity];
      const min = Number(c.min), max = Number(c.max);
      const raw = P.num(hass, c.entity);
      const has = !isNaN(raw);
      const frac = has ? P.clamp((raw - min) / (max - min || 1), 0, 1) : 0;
      const unit = P.unitOf(hass, c.entity, c.unit);
      const name = c.name || (st ? st.attributes.friendly_name : c.entity);
      const valColor = this._segColor(raw);
      const value = has ? P.fmtNumber(raw, c.decimals != null ? Number(c.decimals) : (Math.abs(raw) >= 100 ? 0 : 1)) : '—';

      // Geometry sized so the full 270° arc (ends ~0.7·r below centre) fits.
      const W = 200, H = 176, cx = 100, cy = 100, r = 80, tw = 13;
      const track = arc(cx, cy, r, START, END);
      const [lx, ly] = pt(cx, cy, r, START); // lower-left end
      const [rx, ry] = pt(cx, cy, r, END); // lower-right end

      let bandArcs = '';
      const segs = Array.isArray(c.segments) ? [...c.segments].sort((a, b) => a.from - b.from) : [];
      if (c.style === 'bands' && segs.length) {
        for (let i = 0; i < segs.length; i++) {
          const f0 = P.clamp((segs[i].from - min) / (max - min || 1), 0, 1);
          const f1 = i < segs.length - 1 ? P.clamp((segs[i + 1].from - min) / (max - min || 1), 0, 1) : 1;
          if (f1 <= f0) continue;
          bandArcs += `<path d="${arc(cx, cy, r, degAt(f0), degAt(f1))}" fill="none"
            stroke="${P.resolveAccent(segs[i].color)}" stroke-width="${tw}" stroke-linecap="butt"/>`;
        }
      }

      // Fill mode: progress arc coloured by active band.
      const fillArc = (c.style !== 'bands' && has && frac > 0)
        ? `<path d="${arc(cx, cy, r, START, degAt(frac))}" fill="none" stroke="${valColor}"
             stroke-width="${tw}" stroke-linecap="round" style="transition:stroke-dashoffset .5s"/>`
        : '';

      // Bands mode: needle.
      let needle = '';
      if (c.style === 'bands' && has) {
        const [nx, ny] = pt(cx, cy, r - tw - 4, degAt(frac));
        needle = `<line x1="${cx}" y1="${cy}" x2="${nx.toFixed(1)}" y2="${ny.toFixed(1)}"
                    stroke="var(--_text)" stroke-width="3" stroke-linecap="round" style="transition:all .5s"/>
                  <circle cx="${cx}" cy="${cy}" r="4" fill="var(--_text)"/>`;
      }

      this.shadowRoot.innerHTML = `
        <style>
          ${P.TOKEN_STYLE}
          .prism-card { display:flex; flex-direction:column; align-items:center; justify-content:center; cursor:pointer; }
          svg { width:100%; max-width:230px; height:auto; display:block; }
          .track { stroke: var(--_surface-2); }
          .value { fill: var(--_text); font-weight:750; font-size:34px; letter-spacing:-.5px; }
          .unit { fill: var(--_text-2); font-weight:500; font-size:13px; }
          .end { fill: var(--_text-2); font-weight:500; font-size:11px; }
          .name { font-size:13px; font-weight:600; color:var(--_text-2); margin-top:4px;
                  white-space:nowrap; overflow:hidden; text-overflow:ellipsis; max-width:100%; text-align:center; }
        </style>
        <div class="prism-card" role="button" tabindex="0" aria-label="${P.esc(name)}">
          <svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="xMidYMid meet">
            <path class="track" d="${track}" fill="none" stroke-width="${tw}" stroke-linecap="round"/>
            ${bandArcs}
            ${fillArc}
            ${needle}
            <text class="value" x="${cx}" y="${cy + 2}" text-anchor="middle" dominant-baseline="middle"
                  style="font-family:var(--_font)">${P.esc(value)}</text>
            ${unit ? `<text class="unit" x="${cx}" y="${cy + 26}" text-anchor="middle" style="font-family:var(--_font)">${P.esc(unit)}</text>` : ''}
            <text class="end" x="${(lx - 2).toFixed(0)}" y="${(ly + 14).toFixed(0)}" text-anchor="middle" style="font-family:var(--_font)">${P.esc(P.fmtNumber(min, 0))}</text>
            <text class="end" x="${(rx + 2).toFixed(0)}" y="${(ry + 14).toFixed(0)}" text-anchor="middle" style="font-family:var(--_font)">${P.esc(P.fmtNumber(max, 0))}</text>
          </svg>
          <div class="name">${P.esc(name)}</div>
        </div>`;

      const card = this.shadowRoot.querySelector('.prism-card');
      const tap = () => this.dispatchEvent(new CustomEvent('hass-more-info', {
        detail: { entityId: c.entity }, bubbles: true, composed: true,
      }));
      card.addEventListener('click', tap);
      card.addEventListener('keydown', (e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); tap(); } });
    }
  }

  customElements.define('prism-gauge-card', PrismGaugeCard);
  P.registerCard({
    type: 'prism-gauge-card',
    name: 'Prism Gauge Card',
    description: 'Flat 270° gauge with severity bands (fill or needle).',
  });
})();

/* ===== src/prism-sparkline-card.js ===== */
/**
 * prism-sparkline-card
 * Flat history mini-graph. Header shows the entity name + current value;
 * body is a clean line/area sparkline over a configurable time window with
 * optional min/max markers. Downsamples history for smooth, fast rendering.
 *
 * type: custom:prism-sparkline-card
 */
(function () {
  'use strict';
  const P = window.PrismUI;

  // ── Editor ────────────────────────────────────────────────────────
  class PrismSparklineCardEditor extends P.PrismEditor {
    _fields(stack) {
      const c = this._config;
      stack.append(
        this._picker('Entity (required)', c.entity, (v) => this._patch('entity', v)),
        this._tf('Name (optional)', c.name, (v) => this._patch('name', v)),
        this._tf('Unit override', c.unit, (v) => this._patch('unit', v)),
        this._tf('Decimals', c.decimals, (v) => this._patch('decimals', v), { type: 'number' }),
        this._tf('Window (hours)', c.hours, (v) => this._patch('hours', v), { type: 'number' }),
        this._select('Style', ['area', 'line'], c.style || 'area', (v) => this._patch('style', v)),
        this._accentField(c.accent, (v) => this._patch('accent', v)),
        this._switch('Show current value', c.show_value !== false, (v) => this._patch('show_value', v)),
        this._switch('Show min/max markers', !!c.show_minmax, (v) => this._patch('show_minmax', v)),
        this._hint('Reads recorder history; refreshed every 5 minutes.')
      );
    }
  }
  customElements.define('prism-sparkline-card-editor', PrismSparklineCardEditor);

  // ── Card ──────────────────────────────────────────────────────────
  class PrismSparklineCard extends HTMLElement {
    constructor() {
      super();
      this.attachShadow({ mode: 'open' });
      this._config = null;
      this._hass = null;
      this._history = [];
      this._historyAt = 0;
    }

    setConfig(config) {
      if (!config.entity) throw new Error('prism-sparkline-card: `entity` is required.');
      this._config = { hours: 24, style: 'area', ...config };
      this._history = [];
      this._historyAt = 0;
      if (this._hass) { this._maybeFetch(); this._render(); }
    }

    set hass(hass) {
      const first = !this._hass;
      this._hass = hass;
      this._maybeFetch();
      if (first) this._render(); else this._renderHeader();
    }

    getCardSize() { return 3; }
    getGridOptions() { return { rows: 3, columns: 12, min_rows: 2, min_columns: 4 }; }

    static getConfigElement() { return document.createElement('prism-sparkline-card-editor'); }
    static getStubConfig(hass) {
      const ent = hass ? Object.keys(hass.states).find((e) => e.startsWith('sensor.')) : 'sensor.example';
      return { entity: ent || 'sensor.example', hours: 24, style: 'area', show_value: true };
    }

    async _maybeFetch() {
      if (!this._hass || !this._config) return;
      const now = Date.now();
      if (now - this._historyAt < 5 * 60 * 1000 && this._history.length) return;
      this._historyAt = now;
      const hours = Number(this._config.hours) > 0 ? Number(this._config.hours) : 24;
      const raw = await P.fetchHistory(this._hass, this._config.entity, hours);
      this._history = P.downsample(raw, 300);
      this._render();
    }

    // Cheap header-only refresh on frequent hass updates.
    _renderHeader() {
      const el = this.shadowRoot.querySelector('.cur');
      if (!el || !this._hass) return;
      const c = this._config;
      const raw = P.num(this._hass, c.entity);
      const unit = P.unitOf(this._hass, c.entity, c.unit);
      el.innerHTML = !isNaN(raw)
        ? `${P.esc(P.fmtNumber(raw, c.decimals != null ? Number(c.decimals) : (Math.abs(raw) >= 100 ? 0 : 1)))}<span class="cunit">${unit ? ' ' + P.esc(unit) : ''}</span>`
        : '—';
    }

    _render() {
      if (!this._config || !this._hass) return;
      const c = this._config;
      const hass = this._hass;
      const st = hass.states[c.entity];
      const accent = P.resolveAccent(c.accent);
      const name = c.name || (st ? st.attributes.friendly_name : c.entity);
      const raw = P.num(hass, c.entity);
      const unit = P.unitOf(hass, c.entity, c.unit);
      const cur = !isNaN(raw)
        ? P.fmtNumber(raw, c.decimals != null ? Number(c.decimals) : (Math.abs(raw) >= 100 ? 0 : 1))
        : '—';

      const W = 400, H = 96;
      const sp = P.sparklinePath(this._history, W, H, 4);
      const hasData = this._history.length > 1;

      let minmax = '';
      let markers = '';
      if (hasData && c.show_minmax) {
        // Locate min/max points for dots + labels.
        let lo = this._history[0], hi = this._history[0];
        for (const p of this._history) { if (p.v < lo.v) lo = p; if (p.v > hi.v) hi = p; }
        const t0 = this._history[0].t, t1 = this._history[this._history.length - 1].t;
        const span = t1 - t0 || 1, range = (sp.max - sp.min) || 1;
        const X = (t) => 4 + ((t - t0) / span) * (W - 8);
        const Y = (v) => 4 + (1 - (v - sp.min) / range) * (H - 8);
        markers = `
          <circle cx="${X(hi.t).toFixed(1)}" cy="${Y(hi.v).toFixed(1)}" r="3" fill="${accent}"/>
          <circle cx="${X(lo.t).toFixed(1)}" cy="${Y(lo.v).toFixed(1)}" r="3" fill="${accent}" opacity="0.5"/>`;
        minmax = `<div class="mm"><span>▲ ${P.esc(P.fmtNumber(hi.v, 1))}</span><span>▼ ${P.esc(P.fmtNumber(lo.v, 1))}</span></div>`;
      }

      const dot = hasData
        ? (() => {
            const last = this._history[this._history.length - 1];
            const t0 = this._history[0].t, t1 = last.t;
            const span = t1 - t0 || 1, range = (sp.max - sp.min) || 1;
            const x = 4 + ((last.t - t0) / span) * (W - 8);
            const y = 4 + (1 - (last.v - sp.min) / range) * (H - 8);
            return `<circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="3.5" fill="${accent}"/>`;
          })()
        : '';

      const body = hasData
        ? `<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none" class="graph" aria-hidden="true">
             ${c.style !== 'line' ? `<path d="${sp.area}" fill="${accent}" opacity="0.12"/>` : ''}
             <path d="${sp.line}" fill="none" stroke="${accent}" stroke-width="2.5"
                   stroke-linecap="round" stroke-linejoin="round"/>
             ${markers}${dot}
           </svg>`
        : `<div class="empty">No history yet</div>`;

      this.shadowRoot.innerHTML = `
        <style>
          ${P.TOKEN_STYLE}
          .prism-card { display:flex; flex-direction:column; cursor:pointer; }
          .head { display:flex; align-items:flex-start; justify-content:space-between; gap:8px; margin-bottom:8px; }
          .name { font-size:13px; font-weight:600; color:var(--_text-2);
                  white-space:nowrap; overflow:hidden; text-overflow:ellipsis; }
          .cur { font-size:22px; font-weight:750; letter-spacing:-.02em; color:var(--_text); line-height:1; white-space:nowrap; }
          .cunit { font-size:12px; font-weight:500; color:var(--_text-2); }
          .graph { width:100%; height:96px; flex:1; display:block; min-height:56px; }
          .empty { flex:1; display:flex; align-items:center; justify-content:center; color:var(--_text-2); font-size:12px; }
          .mm { display:flex; justify-content:space-between; font-size:11px; color:var(--_text-2); margin-top:4px; }
        </style>
        <div class="prism-card" role="button" tabindex="0" aria-label="${P.esc(name)}">
          <div class="head">
            <div class="name">${P.esc(name)}</div>
            ${c.show_value !== false ? `<div class="cur">${P.esc(cur)}<span class="cunit">${unit ? ' ' + P.esc(unit) : ''}</span></div>` : ''}
          </div>
          ${body}
          ${minmax}
        </div>`;

      const card = this.shadowRoot.querySelector('.prism-card');
      const tap = () => this.dispatchEvent(new CustomEvent('hass-more-info', {
        detail: { entityId: c.entity }, bubbles: true, composed: true,
      }));
      card.addEventListener('click', tap);
      card.addEventListener('keydown', (e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); tap(); } });
    }
  }

  customElements.define('prism-sparkline-card', PrismSparklineCard);
  P.registerCard({
    type: 'prism-sparkline-card',
    name: 'Prism Sparkline Card',
    description: 'Flat history mini-graph with current value and min/max markers.',
  });
})();

/* ===== src/prism-power-card.js ===== */
/**
 * prism-power-card
 * Flat live power/energy tile. One dominant power value with a load bar for
 * context, a peak-in-window figure, an optional secondary energy total, and
 * an optional recent-power sparkline. Built for real-time energy monitoring
 * (e.g. CT-clamp power sensors) — never a bare number.
 *
 * Two modes:
 *   • load (default) — bar fills 0 → max; colour = accent (or severity band).
 *   • grid           — signed sensor: bar is zero-centred, import right /
 *                      export left, and an Import/Export pill states direction.
 *
 * type: custom:prism-power-card
 */
(function () {
  'use strict';
  const P = window.PrismUI;

  // ── Editor ────────────────────────────────────────────────────────
  class PrismPowerCardEditor extends P.PrismEditor {
    _fields(stack) {
      const c = this._config;
      stack.append(
        this._picker('Power entity (required)', c.entity, (v) => this._patch('entity', v), { domains: ['sensor'] }),
        this._tf('Name (optional)', c.name, (v) => this._patch('name', v)),
        this._tf('Icon (mdi:…)', c.icon, (v) => this._patch('icon', v)),
        this._tf('Unit override', c.unit, (v) => this._patch('unit', v)),
        this._tf('Decimals', c.decimals, (v) => this._patch('decimals', v), { type: 'number' }),
        this._accentField(c.accent, (v) => this._patch('accent', v)),
        this._section('Load bar'),
        this._select('Mode', [
          { value: 'load', label: 'Load (0 → max)' },
          { value: 'grid', label: 'Grid (import / export)' },
        ], c.mode || 'load', (v) => this._patch('mode', v)),
        this._tf('Bar max (blank = auto from window peak)', c.max, (v) => this._patch('max', v), { type: 'number' }),
        this._hint('Grid mode expects a signed sensor: positive = importing, negative = exporting.'),
        this._section('Context'),
        this._picker('Energy total entity (optional)', c.energy_entity, (v) => this._patch('energy_entity', v), { domains: ['sensor'] }),
        this._tf('Energy label', c.energy_label, (v) => this._patch('energy_label', v)),
        this._tf('History window (hours)', c.hours, (v) => this._patch('hours', v), { type: 'number' }),
        this._switch('Show peak in window', c.peak !== false, (v) => this._patch('peak', v)),
        this._switch('Show sparkline', !!c.sparkline, (v) => this._patch('sparkline', v)),
        this._hint('Peak and sparkline read recorder history for the power entity.')
      );
    }
  }
  customElements.define('prism-power-card-editor', PrismPowerCardEditor);

  // ── Card ──────────────────────────────────────────────────────────
  class PrismPowerCard extends HTMLElement {
    constructor() {
      super();
      this.attachShadow({ mode: 'open' });
      this._config = null;
      this._hass = null;
      this._history = [];
      this._historyAt = 0;
    }

    setConfig(config) {
      if (!config.entity) throw new Error('prism-power-card: `entity` is required.');
      this._config = { mode: 'load', ...config };
      this._history = [];
      this._historyAt = 0;
      if (this._hass) this._render();
    }

    set hass(hass) {
      this._hass = hass;
      this._maybeFetchHistory();
      this._render();
    }

    getCardSize() { return this._config?.sparkline ? 4 : 3; }
    getGridOptions() {
      return this._config?.sparkline
        ? { rows: 4, columns: 6, min_rows: 3, min_columns: 4 }
        : { rows: 3, columns: 6, min_rows: 2, min_columns: 4 };
    }

    static getConfigElement() { return document.createElement('prism-power-card-editor'); }
    static getStubConfig(hass) {
      const pick = (kw) => hass && Object.keys(hass.states).find(
        (e) => e.startsWith('sensor.') && (e.includes(kw) || (hass.states[e].attributes.unit_of_measurement || '').match(/^k?W$/))
      );
      const ent = pick('power') || (hass && Object.keys(hass.states).find((e) => e.startsWith('sensor.'))) || 'sensor.example';
      return { entity: ent, mode: 'load', hours: 3, peak: true, sparkline: true, accent: 'amber' };
    }

    _needsHistory() {
      return this._config && (this._config.peak !== false || this._config.sparkline || this._config.max == null);
    }

    async _maybeFetchHistory() {
      if (!this._needsHistory() || !this._hass) return;
      const now = Date.now();
      if (now - this._historyAt < 5 * 60 * 1000 && this._history.length) return; // 5-min cache
      this._historyAt = now;
      const hours = Number(this._config.hours) > 0 ? Number(this._config.hours) : 3;
      const raw = await P.fetchHistory(this._hass, this._config.entity, hours);
      this._history = P.downsample(raw, 200);
      this._render();
    }

    _onTap(entityId) {
      this.dispatchEvent(new CustomEvent('hass-more-info', {
        detail: { entityId }, bubbles: true, composed: true,
      }));
    }

    _render() {
      if (!this._config || !this._hass) return;
      const c = this._config;
      const hass = this._hass;
      const st = hass.states[c.entity];
      const grid = c.mode === 'grid';
      const accent = P.resolveAccent(c.accent);
      const name = c.name || (st ? st.attributes.friendly_name : c.entity);
      const raw = P.num(hass, c.entity);
      const has = !isNaN(raw);
      const unit = P.unitOf(hass, c.entity, c.unit);
      const decimals = c.decimals != null ? Number(c.decimals) : inferDecimals(raw);
      const value = has ? P.fmtNumber(grid ? Math.abs(raw) : raw, decimals) : '—';

      // Window peak (abs, so it also bounds grid mode).
      let peak = NaN;
      for (const p of this._history) { const a = Math.abs(p.v); if (!(a <= peak)) peak = a; }
      if (has) peak = isNaN(peak) ? Math.abs(raw) : Math.max(peak, Math.abs(raw));

      // Bar scale: explicit max wins, else window peak, else current value.
      const scale = Number(c.max) > 0 ? Number(c.max) : (peak > 0 ? peak : (Math.abs(raw) || 1));

      // Direction colour (grid mode): exporting = good, importing = accent.
      const exporting = grid && has && raw < 0;
      const valColor = grid ? (exporting ? 'var(--_good)' : accent) : accent;

      // ── Load bar ──
      let barHtml;
      if (grid) {
        const f = has ? P.clamp(Math.abs(raw) / scale, 0, 1) : 0;
        const half = (f * 50).toFixed(1);
        barHtml = `
          <div class="bar grid">
            <div class="mid"></div>
            ${has ? `<div class="fill" style="${exporting
              ? `right:50%;width:${half}%;background:var(--_good);border-radius:5px 0 0 5px;`
              : `left:50%;width:${half}%;background:${accent};border-radius:0 5px 5px 0;`}"></div>` : ''}
          </div>`;
      } else {
        const f = has ? P.clamp(raw / scale, 0, 1) : 0;
        barHtml = `
          <div class="bar">
            <div class="fill" style="width:${(f * 100).toFixed(1)}%;background:${accent};"></div>
          </div>`;
      }

      // ── Footer meta: pill + peak + energy total ──
      const pill = grid && has
        ? `<span class="pill" style="color:${valColor};background:color-mix(in srgb, ${exporting ? 'var(--_good)' : accent} 15%, transparent)">${exporting ? 'Exporting' : raw > 0 ? 'Importing' : 'Idle'}</span>`
        : '';

      let peakHtml = '';
      if (c.peak !== false && isFinite(peak) && this._history.length) {
        peakHtml = `<span class="meta">Peak ${P.esc(P.fmtNumber(peak, inferDecimals(peak)))} ${P.esc(unit)}</span>`;
      }

      let energyHtml = '';
      if (c.energy_entity && hass.states[c.energy_entity]) {
        const ev = P.num(hass, c.energy_entity);
        const eu = P.unitOf(hass, c.energy_entity, '');
        const elabel = c.energy_label || 'Today';
        energyHtml = `
          <button class="energy" data-entity="${P.esc(c.energy_entity)}" aria-label="${P.esc(elabel)}">
            <span class="e-label">${P.esc(elabel)}</span>
            <span class="e-val">${P.esc(isNaN(ev) ? hass.states[c.energy_entity].state : P.fmtNumber(ev, ev >= 100 ? 0 : 1))}<span class="e-unit"> ${P.esc(eu)}</span></span>
          </button>`;
      }

      // ── Sparkline ──
      let sparkHtml = '';
      if (c.sparkline && this._history.length > 1) {
        const w = 260, h = 38;
        const sp = P.sparklinePath(this._history, w, h, 3);
        // Zero reference line for grid (signed) series when zero is in range.
        let zeroLine = '';
        if (grid && sp.min < 0 && sp.max > 0) {
          const y = (3 + (1 - (0 - sp.min) / (sp.max - sp.min)) * (h - 6)).toFixed(1);
          zeroLine = `<line x1="0" y1="${y}" x2="${w}" y2="${y}" stroke="var(--_border)" stroke-width="1" stroke-dasharray="3 3"/>`;
        }
        sparkHtml = `
          <svg class="spark" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" aria-hidden="true">
            <path d="${sp.area}" fill="${accent}" opacity="0.10"/>
            ${zeroLine}
            <path d="${sp.line}" fill="none" stroke="${accent}" stroke-width="2"
                  stroke-linecap="round" stroke-linejoin="round"/>
          </svg>`;
      }

      const iconHtml = c.icon
        ? `<div class="icon" style="color:${accent}"><ha-icon icon="${P.esc(c.icon)}"></ha-icon></div>`
        : '';

      this.shadowRoot.innerHTML = `
        <style>
          ${P.TOKEN_STYLE}
          .prism-card { display:flex; flex-direction:column; gap:10px; }
          .top { display:flex; align-items:center; gap:10px; }
          .icon { --mdc-icon-size:20px; width:34px; height:34px; border-radius:10px;
                  display:flex; align-items:center; justify-content:center;
                  background:color-mix(in srgb, ${accent} 14%, transparent); flex:none; }
          .label { font-size:13px; font-weight:600; color:var(--_text-2);
                   white-space:nowrap; overflow:hidden; text-overflow:ellipsis; }
          .energy { margin-left:auto; display:flex; flex-direction:column; align-items:flex-end;
                    gap:1px; background:none; border:none; padding:0; cursor:pointer; font:inherit; }
          .e-label { font-size:10px; font-weight:600; letter-spacing:.04em; text-transform:uppercase; color:var(--_text-2); }
          .e-val { font-size:14px; font-weight:700; color:var(--_text); }
          .e-unit { font-size:11px; font-weight:500; color:var(--_text-2); }
          .valrow { display:flex; align-items:baseline; gap:8px; flex-wrap:wrap; cursor:pointer; }
          .value { font-size:36px; font-weight:750; line-height:1; letter-spacing:-.02em; color:${valColor}; }
          .unit { font-size:15px; font-weight:500; color:var(--_text-2); }
          .pill { margin-left:auto; align-self:center; font-size:11px; font-weight:700;
                  padding:3px 9px; border-radius:999px; letter-spacing:.02em; }
          .bar { position:relative; height:10px; border-radius:5px; background:var(--_surface-2); overflow:hidden; }
          .bar .fill { position:absolute; top:0; bottom:0; left:0; border-radius:5px; transition:width .5s, right .5s, left .5s; }
          .bar.grid .mid { position:absolute; top:-1px; bottom:-1px; left:50%; width:1px; background:var(--_border); z-index:1; }
          .footer { display:flex; align-items:center; gap:10px; min-height:16px; }
          .meta { font-size:12px; font-weight:500; color:var(--_text-2); }
          .spark { width:100%; height:38px; display:block; margin-top:2px; }
        </style>
        <div class="prism-card">
          <div class="top">
            ${iconHtml}
            <div class="label">${P.esc(name)}</div>
            ${energyHtml}
          </div>
          <div class="valrow" role="button" tabindex="0" aria-label="${P.esc(name)}">
            <span class="value">${P.esc(value)}</span>
            ${unit && has ? `<span class="unit">${P.esc(unit)}</span>` : ''}
            ${pill}
          </div>
          ${barHtml}
          ${(peakHtml || pill) ? `<div class="footer">${peakHtml}</div>` : ''}
          ${sparkHtml}
        </div>`;

      const valrow = this.shadowRoot.querySelector('.valrow');
      const tap = () => this._onTap(c.entity);
      valrow.addEventListener('click', tap);
      valrow.addEventListener('keydown', (e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); tap(); } });
      const energyBtn = this.shadowRoot.querySelector('.energy');
      if (energyBtn) energyBtn.addEventListener('click', () => this._onTap(energyBtn.dataset.entity));
    }
  }

  // Sensible default decimals based on magnitude (W vs kW).
  function inferDecimals(v) {
    const a = Math.abs(v);
    if (isNaN(a)) return 0;
    if (a >= 100) return 0;
    if (a >= 10) return 1;
    return 2;
  }

  customElements.define('prism-power-card', PrismPowerCard);
  P.registerCard({
    type: 'prism-power-card',
    name: 'Prism Power Card',
    description: 'Live power tile with load bar, peak, energy total, and grid import/export mode.',
  });
})();

/* ===== src/prism-bar-card.js ===== */
/**
 * prism-bar-card
 * Flat horizontal bar chart comparing several entities against a shared
 * scale. Each row is a labelled bar with its value; the largest sets the
 * scale (or pin an explicit max). Built for breakdowns — power per circuit,
 * energy per room, humidity per sensor — never a bare list of numbers.
 *
 * Bar colour resolves per row: explicit `color` → severity `segments`
 * (by value) → the card accent.
 *
 * type: custom:prism-bar-card
 */
(function () {
  'use strict';
  const P = window.PrismUI;

  // Normalise a bar entry to { entity, name?, color?, icon? }.
  function normBar(b) {
    if (typeof b === 'string') return { entity: b };
    return { ...b };
  }

  // ── Editor ────────────────────────────────────────────────────────
  class PrismBarCardEditor extends P.PrismEditor {
    _bars() {
      const list = Array.isArray(this._config.entities) ? this._config.entities : [];
      return list.map(normBar);
    }

    _setBars(bars) {
      const cfg = { ...this._config };
      cfg.entities = bars.map((b) => {
        const o = { entity: b.entity || '' };
        if (b.name) o.name = b.name;
        if (b.color) o.color = b.color;
        if (b.icon) o.icon = b.icon;
        // collapse to a plain string when only an entity is set
        return b.name || b.color || b.icon ? o : (o.entity || o);
      });
      this._fire(cfg);
    }

    // Re-render fields and re-bind hass to any freshly created pickers.
    _rerender() {
      this._render();
      if (this._hass) {
        this.shadowRoot.querySelectorAll('ha-entity-picker').forEach((p) => { p.hass = this._hass; });
      }
    }

    _fields(stack) {
      const c = this._config;
      stack.append(
        this._tf('Title (optional)', c.title, (v) => this._patch('title', v)),
        this._tf('Unit override', c.unit, (v) => this._patch('unit', v)),
        this._tf('Decimals', c.decimals, (v) => this._patch('decimals', v), { type: 'number' }),
        this._tf('Minimum (baseline)', c.min, (v) => this._patch('min', v), { type: 'number' }),
        this._tf('Maximum (blank = auto from largest)', c.max, (v) => this._patch('max', v), { type: 'number' }),
        this._accentField(c.accent, (v) => this._patch('accent', v)),
        this._switch('Sort by value (descending)', !!c.sort, (v) => this._patch('sort', v)),
        this._switch('Show values', c.show_value !== false, (v) => this._patch('show_value', v)),
        this._section('Entities'),
        this._barsField(),
        this._section('Severity bands (optional)'),
        this._hint('JSON array, e.g. [{"from":0,"color":"green"},{"from":1000,"color":"amber"},{"from":2000,"color":"red"}]. Colours a bar by its value unless the bar has its own colour.'),
        this._segmentsField(c.segments)
      );
    }

    _barsField() {
      const bars = this._bars();
      const wrap = document.createElement('div');
      wrap.className = 'bars';

      bars.forEach((bar, i) => {
        const row = document.createElement('div');
        row.className = 'bar-row';
        row.appendChild(this._picker(`Entity ${i + 1}`, bar.entity, (v) => {
          const b = this._bars(); b[i].entity = v; this._setBars(b);
        }));
        const sub = document.createElement('div');
        sub.className = 'bar-sub';
        sub.append(
          this._tf('Name', bar.name, (v) => { const b = this._bars(); b[i].name = v; this._setBars(b); }),
          this._colorField(bar.color, (v) => { const b = this._bars(); b[i].color = v; this._setBars(b); })
        );
        const rm = document.createElement('button');
        rm.type = 'button';
        rm.className = 'rm';
        rm.textContent = 'Remove';
        rm.addEventListener('click', () => { const b = this._bars(); b.splice(i, 1); this._setBars(b); this._rerender(); });
        row.append(sub, rm);
        wrap.appendChild(row);
      });

      const add = document.createElement('button');
      add.type = 'button';
      add.className = 'add';
      add.textContent = '+ Add entity';
      add.addEventListener('click', () => { const b = this._bars(); b.push({ entity: '' }); this._setBars(b); this._rerender(); });
      wrap.appendChild(add);
      return wrap;
    }

    // Compact colour picker: "accent" (blank) or a custom colour.
    _colorField(value, onChange) {
      const wrap = document.createElement('div');
      wrap.className = 'field';
      const lbl = document.createElement('label');
      lbl.className = 'lbl';
      lbl.textContent = 'Colour';
      const row = document.createElement('div');
      row.className = 'accent-row';
      const sel = document.createElement('select');
      sel.className = 'sel';
      const custom = value != null && value !== '' && !P.ACCENTS[value];
      ['accent', ...Object.keys(P.ACCENTS), 'custom'].forEach((name) => {
        const o = document.createElement('option');
        o.value = name; o.textContent = name;
        if ((name === value) || (name === 'accent' && (value == null || value === '')) || (name === 'custom' && custom)) o.selected = true;
        sel.appendChild(o);
      });
      const color = document.createElement('input');
      color.type = 'color'; color.className = 'color';
      color.value = P.ACCENTS[value] || (custom ? value : '#3aa0e8');
      color.style.display = custom ? 'inline-block' : 'none';
      sel.addEventListener('change', (e) => {
        const v = e.target.value;
        if (v === 'custom') { color.style.display = 'inline-block'; onChange(color.value); }
        else { color.style.display = 'none'; onChange(v === 'accent' ? '' : v); }
      });
      color.addEventListener('input', (e) => onChange(e.target.value));
      row.append(sel, color);
      wrap.append(lbl, row);
      return wrap;
    }

    _segmentsField(value) {
      const wrap = document.createElement('div');
      wrap.className = 'field';
      const ta = document.createElement('textarea');
      ta.rows = 4; ta.className = 'sel'; ta.style.fontFamily = 'monospace';
      ta.value = value ? JSON.stringify(value, null, 2) : '';
      ta.placeholder = '[]';
      ta.addEventListener('change', (e) => {
        const t = e.target.value.trim();
        if (!t) { this._patch('segments', ''); return; }
        try { this._patch('segments', JSON.parse(t)); } catch (_) { /* wait for valid JSON */ }
      });
      wrap.appendChild(ta);
      return wrap;
    }

    _baseStyle() {
      const style = super._baseStyle();
      style.textContent += `
        .bars { display:flex; flex-direction:column; gap:14px; }
        .bar-row { display:flex; flex-direction:column; gap:8px; padding:12px; border:1px solid var(--divider-color,rgba(0,0,0,.08)); border-radius:8px; }
        .bar-sub { display:flex; gap:8px; }
        .bar-sub > .field:first-child { flex:1; }
        .rm { align-self:flex-start; font:500 12px/1 inherit; cursor:pointer; color:var(--error-color,#c62828); background:none; border:none; padding:2px 0; }
        .add { align-self:flex-start; font:600 13px/1 inherit; cursor:pointer; color:var(--primary-color,#3aa0e8); background:none; border:1px dashed var(--divider-color,#ccc); border-radius:8px; padding:10px 14px; }
      `;
      return style;
    }
  }
  customElements.define('prism-bar-card-editor', PrismBarCardEditor);

  // ── Card ──────────────────────────────────────────────────────────
  class PrismBarCard extends HTMLElement {
    constructor() {
      super();
      this.attachShadow({ mode: 'open' });
      this._config = null;
      this._hass = null;
    }

    setConfig(config) {
      const list = config.entities || config.bars;
      if (!Array.isArray(list) || !list.length) {
        throw new Error('prism-bar-card: `entities` must be a non-empty list.');
      }
      this._config = { min: 0, show_value: true, ...config, entities: list };
      if (this._hass) this._render();
    }

    set hass(hass) { this._hass = hass; this._render(); }

    getCardSize() { return 1 + (this._config?.entities?.length || 1); }
    getGridOptions() {
      const n = this._config?.entities?.length || 1;
      return { rows: Math.max(2, n + (this._config?.title ? 2 : 1)), columns: 6, min_rows: 2, min_columns: 4 };
    }

    static getConfigElement() { return document.createElement('prism-bar-card-editor'); }
    static getStubConfig(hass) {
      const sensors = hass ? Object.keys(hass.states).filter((e) => e.startsWith('sensor.') && !isNaN(parseFloat(hass.states[e].state))).slice(0, 3) : [];
      return { title: 'Comparison', entities: sensors.length ? sensors : ['sensor.example'], sort: true, accent: 'blue' };
    }

    _segColor(value) {
      const segs = Array.isArray(this._config.segments) ? this._config.segments : [];
      if (!segs.length) return null;
      const sorted = [...segs].sort((a, b) => a.from - b.from);
      let col = P.resolveAccent(sorted[0].color);
      for (const s of sorted) if (value >= s.from) col = P.resolveAccent(s.color);
      return col;
    }

    _render() {
      if (!this._config || !this._hass) return;
      const c = this._config;
      const hass = this._hass;
      const accent = P.resolveAccent(c.accent);
      const min = Number(c.min) || 0;

      // Build row models.
      let rows = c.entities.map(normBar).map((b) => {
        const st = hass.states[b.entity];
        const raw = P.num(hass, b.entity);
        const has = !isNaN(raw);
        return {
          entity: b.entity,
          name: b.name || (st ? st.attributes.friendly_name : b.entity),
          icon: b.icon,
          color: b.color ? P.resolveAccent(b.color) : null,
          raw, has,
          unit: P.unitOf(hass, b.entity, c.unit),
        };
      });
      if (c.sort) rows = rows.slice().sort((a, b) => (b.has ? b.raw : -Infinity) - (a.has ? a.raw : -Infinity));

      // Shared scale.
      let max = Number(c.max);
      if (!(max > min)) {
        max = -Infinity;
        for (const r of rows) if (r.has && r.raw > max) max = r.raw;
        if (!(max > min)) max = min + 1;
      }

      const dec = (v) => c.decimals != null ? Number(c.decimals) : (Math.abs(v) >= 100 ? 0 : Math.abs(v) >= 10 ? 1 : 2);

      const rowsHtml = rows.map((r) => {
        const frac = r.has ? P.clamp((r.raw - min) / (max - min || 1), 0, 1) : 0;
        const col = r.color || this._segColor(r.raw) || accent;
        const valTxt = r.has ? `${P.esc(P.fmtNumber(r.raw, dec(r.raw)))}${r.unit ? `<span class="u"> ${P.esc(r.unit)}</span>` : ''}` : '—';
        const iconHtml = r.icon ? `<ha-icon class="ic" icon="${P.esc(r.icon)}" style="color:${col}"></ha-icon>` : '';
        return `
          <button class="row" data-entity="${P.esc(r.entity)}" aria-label="${P.esc(r.name)}">
            <div class="line">
              <span class="nm">${iconHtml}${P.esc(r.name)}</span>
              ${c.show_value !== false ? `<span class="val">${valTxt}</span>` : ''}
            </div>
            <div class="track"><div class="fill" style="width:${(frac * 100).toFixed(1)}%;background:${col};"></div></div>
          </button>`;
      }).join('');

      this.shadowRoot.innerHTML = `
        <style>
          ${P.TOKEN_STYLE}
          .prism-card { display:flex; flex-direction:column; }
          .rows { display:flex; flex-direction:column; gap:14px; }
          .row { display:flex; flex-direction:column; gap:6px; background:none; border:none; padding:0;
                 font:inherit; color:inherit; text-align:left; cursor:pointer; width:100%; }
          .line { display:flex; align-items:baseline; justify-content:space-between; gap:10px; }
          .nm { font-size:13px; font-weight:600; color:var(--_text); display:flex; align-items:center; gap:6px;
                white-space:nowrap; overflow:hidden; text-overflow:ellipsis; min-width:0; }
          .ic { --mdc-icon-size:16px; width:16px; height:16px; flex:none; }
          .val { font-size:14px; font-weight:700; color:var(--_text); white-space:nowrap; flex:none; }
          .val .u { font-size:11px; font-weight:500; color:var(--_text-2); }
          .track { position:relative; height:9px; border-radius:5px; background:var(--_surface-2); overflow:hidden; }
          .fill { position:absolute; top:0; bottom:0; left:0; border-radius:5px; transition:width .5s; min-width:2px; }
        </style>
        <div class="prism-card">
          ${c.title ? `<div class="prism-head"><div class="prism-title">${P.esc(c.title)}</div></div>` : ''}
          <div class="rows">${rowsHtml}</div>
        </div>`;

      this.shadowRoot.querySelectorAll('.row').forEach((el) => {
        el.addEventListener('click', () => this.dispatchEvent(new CustomEvent('hass-more-info', {
          detail: { entityId: el.dataset.entity }, bubbles: true, composed: true,
        })));
      });
    }
  }

  customElements.define('prism-bar-card', PrismBarCard);
  P.registerCard({
    type: 'prism-bar-card',
    name: 'Prism Bar Card',
    description: 'Horizontal bar chart comparing entities on a shared scale, with per-bar colour and severity bands.',
  });
})();

/* ===== src/prism-linear-gauge-card.js ===== */
/**
 * prism-linear-gauge-card
 * Flat horizontal gauge: a single value on a linear min→max scale with
 * configurable severity bands. Two looks (mirrors the radial gauge):
 *   • fill  (default) — track + progress bar coloured by the active band.
 *   • bands           — full band strip + a marker at the current value.
 * Dominant value + unit on the right, name on the left, min/max end labels.
 *
 * type: custom:prism-linear-gauge-card
 */
(function () {
  'use strict';
  const P = window.PrismUI;

  // ── Editor ────────────────────────────────────────────────────────
  class PrismLinearGaugeCardEditor extends P.PrismEditor {
    _fields(stack) {
      const c = this._config;
      stack.append(
        this._picker('Entity (required)', c.entity, (v) => this._patch('entity', v)),
        this._tf('Name (optional)', c.name, (v) => this._patch('name', v)),
        this._tf('Icon (mdi:…)', c.icon, (v) => this._patch('icon', v)),
        this._tf('Unit override', c.unit, (v) => this._patch('unit', v)),
        this._tf('Minimum', c.min, (v) => this._patch('min', v), { type: 'number' }),
        this._tf('Maximum', c.max, (v) => this._patch('max', v), { type: 'number' }),
        this._tf('Decimals', c.decimals, (v) => this._patch('decimals', v), { type: 'number' }),
        this._select('Style', ['fill', 'bands'], c.style || 'fill', (v) => this._patch('style', v)),
        this._accentField(c.accent, (v) => this._patch('accent', v)),
        this._switch('Show min / max labels', c.show_minmax !== false, (v) => this._patch('show_minmax', v)),
        this._section('Severity bands'),
        this._hint('JSON array, e.g. [{"from":0,"color":"green"},{"from":60,"color":"amber"},{"from":85,"color":"red"}]. Colours accept preset names or hex.'),
        this._segmentsField(c.segments)
      );
    }

    _segmentsField(value) {
      const wrap = document.createElement('div');
      wrap.className = 'field';
      const ta = document.createElement('textarea');
      ta.rows = 5; ta.className = 'sel'; ta.style.fontFamily = 'monospace';
      ta.value = JSON.stringify(value ?? [], null, 2);
      ta.addEventListener('change', (e) => {
        try { this._patch('segments', JSON.parse(e.target.value)); } catch (_) { /* wait for valid JSON */ }
      });
      wrap.appendChild(ta);
      return wrap;
    }
  }
  customElements.define('prism-linear-gauge-card-editor', PrismLinearGaugeCardEditor);

  // ── Card ──────────────────────────────────────────────────────────
  class PrismLinearGaugeCard extends HTMLElement {
    constructor() {
      super();
      this.attachShadow({ mode: 'open' });
      this._config = null;
      this._hass = null;
    }

    setConfig(config) {
      if (!config.entity) throw new Error('prism-linear-gauge-card: `entity` is required.');
      this._config = { min: 0, max: 100, style: 'fill', ...config };
      if (this._hass) this._render();
    }

    set hass(hass) { this._hass = hass; this._render(); }

    getCardSize() { return 2; }
    getGridOptions() { return { rows: 2, columns: 6, min_rows: 2, min_columns: 3 }; }

    static getConfigElement() { return document.createElement('prism-linear-gauge-card-editor'); }
    static getStubConfig(hass) {
      const ent = hass ? Object.keys(hass.states).find((e) => e.startsWith('sensor.')) : 'sensor.example';
      return {
        entity: ent || 'sensor.example', min: 0, max: 100, style: 'fill',
        segments: [{ from: 0, color: 'green' }, { from: 60, color: 'amber' }, { from: 85, color: 'red' }],
      };
    }

    _segColor(value) {
      const segs = Array.isArray(this._config.segments) ? this._config.segments : [];
      if (!segs.length) return P.resolveAccent(this._config.accent);
      const sorted = [...segs].sort((a, b) => a.from - b.from);
      let col = P.resolveAccent(sorted[0].color);
      for (const s of sorted) if (value >= s.from) col = P.resolveAccent(s.color);
      return col;
    }

    _render() {
      if (!this._config || !this._hass) return;
      const c = this._config;
      const hass = this._hass;
      const st = hass.states[c.entity];
      const bands = c.style === 'bands';
      const min = Number(c.min), max = Number(c.max);
      const span = (max - min) || 1;
      const raw = P.num(hass, c.entity);
      const has = !isNaN(raw);
      const frac = has ? P.clamp((raw - min) / span, 0, 1) : 0;
      const unit = P.unitOf(hass, c.entity, c.unit);
      const name = c.name || (st ? st.attributes.friendly_name : c.entity);
      const valColor = this._segColor(raw);
      const value = has ? P.fmtNumber(raw, c.decimals != null ? Number(c.decimals) : (Math.abs(raw) >= 100 ? 0 : 1)) : '—';

      // Band strip (bands style): coloured segments across the scale.
      let bandStrip = '';
      const segs = Array.isArray(c.segments) ? [...c.segments].sort((a, b) => a.from - b.from) : [];
      if (bands && segs.length) {
        bandStrip = segs.map((s, i) => {
          const f0 = P.clamp((s.from - min) / span, 0, 1);
          const f1 = i < segs.length - 1 ? P.clamp((segs[i + 1].from - min) / span, 0, 1) : 1;
          const w = Math.max(0, f1 - f0) * 100;
          return w > 0 ? `<div style="width:${w.toFixed(2)}%;background:${P.resolveAccent(s.color)};"></div>` : '';
        }).join('');
      }

      // Fill style: progress bar coloured by active band.
      const fill = (!bands && has)
        ? `<div class="fill" style="width:${(frac * 100).toFixed(1)}%;background:${valColor};"></div>` : '';

      // Marker (bands style) at the current value.
      const marker = (bands && has)
        ? `<div class="marker" style="left:${(frac * 100).toFixed(1)}%;"></div>` : '';

      const iconHtml = c.icon
        ? `<span class="icon" style="color:${valColor}"><ha-icon icon="${P.esc(c.icon)}"></ha-icon></span>` : '';

      this.shadowRoot.innerHTML = `
        <style>
          ${P.TOKEN_STYLE}
          .prism-card { display:flex; flex-direction:column; justify-content:center; gap:10px; cursor:pointer; }
          .top { display:flex; align-items:baseline; justify-content:space-between; gap:10px; }
          .name { font-size:13px; font-weight:600; color:var(--_text-2); display:flex; align-items:center; gap:6px;
                  white-space:nowrap; overflow:hidden; text-overflow:ellipsis; min-width:0; }
          .icon { --mdc-icon-size:18px; width:18px; height:18px; flex:none; }
          .val { font-size:26px; font-weight:750; letter-spacing:-.02em; color:${valColor}; white-space:nowrap; flex:none; line-height:1; }
          .val .u { font-size:13px; font-weight:500; color:var(--_text-2); margin-left:3px; }
          .track { position:relative; height:12px; border-radius:6px; background:var(--_surface-2); overflow:hidden; display:flex; }
          .track > div { height:100%; }
          .fill { position:absolute; top:0; bottom:0; left:0; border-radius:6px; transition:width .5s; min-width:2px; }
          .marker { position:absolute; top:-3px; bottom:-3px; width:3px; border-radius:2px; background:var(--_text);
                    transform:translateX(-50%); transition:left .5s; box-shadow:0 0 0 2px var(--_surface); }
          .ends { display:flex; justify-content:space-between; font-size:11px; font-weight:500; color:var(--_text-2); margin-top:-2px; }
        </style>
        <div class="prism-card" role="button" tabindex="0" aria-label="${P.esc(name)}">
          <div class="top">
            <span class="name">${iconHtml}${P.esc(name)}</span>
            <span class="val">${P.esc(value)}${unit && has ? `<span class="u">${P.esc(unit)}</span>` : ''}</span>
          </div>
          <div class="track">${bandStrip}${fill}${marker}</div>
          ${c.show_minmax !== false ? `<div class="ends"><span>${P.esc(P.fmtNumber(min, 0))}</span><span>${P.esc(P.fmtNumber(max, 0))}</span></div>` : ''}
        </div>`;

      const card = this.shadowRoot.querySelector('.prism-card');
      const tap = () => this.dispatchEvent(new CustomEvent('hass-more-info', {
        detail: { entityId: c.entity }, bubbles: true, composed: true,
      }));
      card.addEventListener('click', tap);
      card.addEventListener('keydown', (e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); tap(); } });
    }
  }

  customElements.define('prism-linear-gauge-card', PrismLinearGaugeCard);
  P.registerCard({
    type: 'prism-linear-gauge-card',
    name: 'Prism Linear Gauge Card',
    description: 'Flat horizontal gauge with severity bands (fill bar or band strip + marker).',
  });
})();

/* ===== src/prism-entities-card.js ===== */
/**
 * prism-entities-card
 * Flat entity list: one row per entity — icon, name, optional secondary
 * line, and a right-aligned value (or a flat toggle for actionable
 * domains). Data-first: numeric states are formatted with their unit and
 * kept prominent. Tap a row for more-info; toggles act in place.
 *
 * type: custom:prism-entities-card
 */
(function () {
  'use strict';
  const P = window.PrismUI;

  const TOGGLE_DOMAINS = ['light', 'switch', 'fan', 'input_boolean', 'humidifier', 'siren'];
  const OFF_STATES = ['off', 'unavailable', 'unknown', 'idle', 'closed', 'none', ''];

  const domainOf = (id) => (id || '').split('.')[0];
  const titleCase = (s) => String(s).replace(/_/g, ' ').replace(/\b\w/g, (m) => m.toUpperCase());

  function normRow(r) {
    if (typeof r === 'string') return { entity: r };
    return { ...r };
  }

  // Short relative time: "now", "3m", "2h", "4d".
  function relTime(iso) {
    const t = Date.parse(iso);
    if (isNaN(t)) return '';
    const s = Math.max(0, (Date.now() - t) / 1000);
    if (s < 45) return 'now';
    if (s < 3600) return `${Math.round(s / 60)}m ago`;
    if (s < 86400) return `${Math.round(s / 3600)}h ago`;
    return `${Math.round(s / 86400)}d ago`;
  }

  // ── Editor ────────────────────────────────────────────────────────
  class PrismEntitiesCardEditor extends P.PrismEditor {
    _rows() {
      const list = Array.isArray(this._config.entities) ? this._config.entities : [];
      return list.map(normRow);
    }

    _setRows(rows) {
      const cfg = { ...this._config };
      cfg.entities = rows.map((r) => {
        const o = { entity: r.entity || '' };
        if (r.name) o.name = r.name;
        if (r.icon) o.icon = r.icon;
        if (r.secondary) o.secondary = r.secondary;
        return r.name || r.icon || r.secondary ? o : (o.entity || o);
      });
      this._fire(cfg);
    }

    _rerender() {
      this._render();
      if (this._hass) this.shadowRoot.querySelectorAll('ha-entity-picker').forEach((p) => { p.hass = this._hass; });
    }

    _fields(stack) {
      const c = this._config;
      stack.append(
        this._tf('Title (optional)', c.title, (v) => this._patch('title', v)),
        this._accentField(c.accent, (v) => this._patch('accent', v)),
        this._switch('Show icons', c.show_icons !== false, (v) => this._patch('show_icons', v)),
        this._switch('Colour icon by state', c.state_color !== false, (v) => this._patch('state_color', v)),
        this._select('Secondary line', [
          { value: '', label: 'None' },
          { value: 'last-changed', label: 'Last changed' },
          { value: 'last-updated', label: 'Last updated' },
        ], c.secondary || '', (v) => this._patch('secondary', v)),
        this._section('Entities'),
        this._rowsField()
      );
    }

    _rowsField() {
      const rows = this._rows();
      const wrap = document.createElement('div');
      wrap.className = 'bars';
      rows.forEach((row, i) => {
        const box = document.createElement('div');
        box.className = 'bar-row';
        box.appendChild(this._picker(`Entity ${i + 1}`, row.entity, (v) => {
          const r = this._rows(); r[i].entity = v; this._setRows(r);
        }));
        const sub = document.createElement('div');
        sub.className = 'bar-sub';
        sub.append(
          this._tf('Name', row.name, (v) => { const r = this._rows(); r[i].name = v; this._setRows(r); }),
          this._tf('Icon (mdi:…)', row.icon, (v) => { const r = this._rows(); r[i].icon = v; this._setRows(r); })
        );
        const rm = document.createElement('button');
        rm.type = 'button'; rm.className = 'rm'; rm.textContent = 'Remove';
        rm.addEventListener('click', () => { const r = this._rows(); r.splice(i, 1); this._setRows(r); this._rerender(); });
        box.append(sub, rm);
        wrap.appendChild(box);
      });
      const add = document.createElement('button');
      add.type = 'button'; add.className = 'add'; add.textContent = '+ Add entity';
      add.addEventListener('click', () => { const r = this._rows(); r.push({ entity: '' }); this._setRows(r); this._rerender(); });
      wrap.appendChild(add);
      return wrap;
    }

    _baseStyle() {
      const style = super._baseStyle();
      style.textContent += `
        .bars { display:flex; flex-direction:column; gap:14px; }
        .bar-row { display:flex; flex-direction:column; gap:8px; padding:12px; border:1px solid var(--divider-color,rgba(0,0,0,.08)); border-radius:8px; }
        .bar-sub { display:flex; gap:8px; }
        .bar-sub > .field { flex:1; }
        .rm { align-self:flex-start; font:500 12px/1 inherit; cursor:pointer; color:var(--error-color,#c62828); background:none; border:none; padding:2px 0; }
        .add { align-self:flex-start; font:600 13px/1 inherit; cursor:pointer; color:var(--primary-color,#3aa0e8); background:none; border:1px dashed var(--divider-color,#ccc); border-radius:8px; padding:10px 14px; }
      `;
      return style;
    }
  }
  customElements.define('prism-entities-card-editor', PrismEntitiesCardEditor);

  // ── Card ──────────────────────────────────────────────────────────
  class PrismEntitiesCard extends HTMLElement {
    constructor() {
      super();
      this.attachShadow({ mode: 'open' });
      this._config = null;
      this._hass = null;
    }

    setConfig(config) {
      const list = config.entities;
      if (!Array.isArray(list) || !list.length) {
        throw new Error('prism-entities-card: `entities` must be a non-empty list.');
      }
      this._config = { show_icons: true, state_color: true, ...config, entities: list };
      if (this._hass) this._render();
    }

    set hass(hass) { this._hass = hass; this._render(); }

    getCardSize() { return 1 + (this._config?.entities?.length || 1); }
    getGridOptions() {
      const n = this._config?.entities?.length || 1;
      return { rows: Math.max(2, n + (this._config?.title ? 2 : 1)), columns: 6, min_rows: 2, min_columns: 4 };
    }

    static getConfigElement() { return document.createElement('prism-entities-card-editor'); }
    static getStubConfig(hass) {
      const ids = hass ? Object.keys(hass.states).filter((e) => /^(light|switch|sensor)\./.test(e)).slice(0, 4) : [];
      return { title: 'Entities', entities: ids.length ? ids : ['sensor.example'], accent: 'blue' };
    }

    _isToggle(row, domain) {
      if (row.toggle === false) return false;
      if (row.toggle === true) return true;
      return TOGGLE_DOMAINS.includes(domain);
    }

    _isActive(state) {
      return !OFF_STATES.includes(String(state).toLowerCase());
    }

    _moreInfo(entityId) {
      this.dispatchEvent(new CustomEvent('hass-more-info', {
        detail: { entityId }, bubbles: true, composed: true,
      }));
    }

    _toggle(entityId) {
      if (this._hass && this._hass.callService) {
        this._hass.callService('homeassistant', 'toggle', { entity_id: entityId });
      }
    }

    _render() {
      if (!this._config || !this._hass) return;
      const c = this._config;
      const hass = this._hass;
      const accent = P.resolveAccent(c.accent);
      const showIcons = c.show_icons !== false;

      const rowsHtml = c.entities.map(normRow).map((row, i) => {
        const st = hass.states[row.entity];
        const domain = domainOf(row.entity);
        const name = row.name || (st ? st.attributes.friendly_name : row.entity);
        const missing = !st;
        const raw = P.num(hass, row.entity);
        const isNum = !isNaN(raw);
        const active = st && this._isActive(st.state);
        const isToggle = st && this._isToggle(row, domain);

        // Icon: explicit → entity's → domain default handled by ha-icon fallback.
        const icon = row.icon || (st && st.attributes.icon) || null;
        const iconColor = c.state_color !== false ? (active ? accent : 'var(--_text-2)') : 'var(--_text-2)';
        const iconHtml = showIcons
          ? `<span class="ic" style="color:${iconColor}">${icon ? `<ha-icon icon="${P.esc(icon)}"></ha-icon>` : ''}</span>`
          : '';

        // Secondary line.
        let secondary = '';
        const sk = row.secondary || c.secondary;
        if (sk === 'last-changed' && st) secondary = relTime(st.last_changed);
        else if (sk === 'last-updated' && st) secondary = relTime(st.last_updated);
        else if (sk && st && st.attributes[sk] != null) secondary = String(st.attributes[sk]);

        // Right side: toggle control or state value.
        let right;
        if (isToggle) {
          right = `<button class="tgl${active ? ' on' : ''}" data-toggle="${P.esc(row.entity)}" role="switch"
                     aria-checked="${active ? 'true' : 'false'}" aria-label="${P.esc(name)}"><span class="knob"></span></button>`;
        } else {
          const unit = P.unitOf(hass, row.entity, null);
          const val = missing ? '—'
            : isNum ? `${P.esc(P.fmtNumber(raw, Math.abs(raw) >= 100 ? 0 : Math.abs(raw) >= 10 ? 1 : 2))}${unit ? `<span class="u"> ${P.esc(unit)}</span>` : ''}`
            : `${P.esc(titleCase(st.state))}`;
          right = `<span class="val${active ? ' active' : ''}">${val}</span>`;
        }

        return `
          <div class="row${missing ? ' missing' : ''}" data-entity="${P.esc(row.entity)}" data-i="${i}">
            ${iconHtml}
            <span class="txt">
              <span class="nm">${P.esc(name)}</span>
              ${secondary ? `<span class="sec">${P.esc(secondary)}</span>` : ''}
            </span>
            ${right}
          </div>`;
      }).join('');

      this.shadowRoot.innerHTML = `
        <style>
          ${P.TOKEN_STYLE}
          .prism-card { display:flex; flex-direction:column; }
          .rows { display:flex; flex-direction:column; }
          .row { display:flex; align-items:center; gap:12px; padding:10px 0; cursor:pointer;
                 border-top:1px solid var(--_border); }
          .row:first-child { border-top:none; }
          .row.missing { opacity:.5; }
          .ic { --mdc-icon-size:22px; width:26px; height:26px; flex:none; display:flex; align-items:center; justify-content:center; }
          .txt { display:flex; flex-direction:column; gap:1px; min-width:0; flex:1; }
          .nm { font-size:14px; font-weight:600; color:var(--_text); white-space:nowrap; overflow:hidden; text-overflow:ellipsis; }
          .sec { font-size:11px; font-weight:500; color:var(--_text-2); white-space:nowrap; overflow:hidden; text-overflow:ellipsis; }
          .val { font-size:14px; font-weight:600; color:var(--_text-2); white-space:nowrap; flex:none; }
          .val.active { color:var(--_text); }
          .val .u { font-size:11px; font-weight:500; color:var(--_text-2); }
          .tgl { flex:none; width:40px; height:22px; border-radius:999px; border:none; padding:0; cursor:pointer;
                 background:var(--_surface-2); position:relative; transition:background .2s; }
          .tgl .knob { position:absolute; top:2px; left:2px; width:18px; height:18px; border-radius:50%;
                       background:#fff; box-shadow:0 1px 2px rgba(0,0,0,.25); transition:left .2s; }
          .tgl.on { background:${accent}; }
          .tgl.on .knob { left:20px; }
        </style>
        <div class="prism-card">
          ${c.title ? `<div class="prism-head"><div class="prism-title">${P.esc(c.title)}</div></div>` : ''}
          <div class="rows">${rowsHtml}</div>
        </div>`;

      this.shadowRoot.querySelectorAll('.row').forEach((el) => {
        el.addEventListener('click', (e) => {
          if (e.target.closest('.tgl')) return; // toggle handles itself
          this._moreInfo(el.dataset.entity);
        });
      });
      this.shadowRoot.querySelectorAll('.tgl').forEach((el) => {
        el.addEventListener('click', (e) => { e.stopPropagation(); this._toggle(el.dataset.toggle); });
      });
    }
  }

  customElements.define('prism-entities-card', PrismEntitiesCard);
  P.registerCard({
    type: 'prism-entities-card',
    name: 'Prism Entities Card',
    description: 'Flat entity list with icons, values, flat toggles, and optional secondary info.',
  });
})();
